### PR TITLE
Add hosting_saas dependency and check to avoid double-cloning

### PR DESCRIPTION
**Pull request by GuiguiSurLinux**
I "un-hardcoded" the values used to clone the site. This is a preliminary step towards separating the civicrm functionnality. I also included the check to avoid overwriting the task when it's ongoing or pending.

### CODE REVIEW

**Comment by GuiguiSurLinux** [comment]
I forgot to remove the mechanism to test without civi on line 218... Not sure what to do with that.

**Comment by GuiguiSurLinux** [comment]
Ok I pushed the return lower so that it'll at least check if an invoice ID is included. I'll be creating a new branch to split the civi dependency.

**Comment by GuiguiSurLinux** [comment]
This is the general direction I'm headed in with this: https://github.com/gboudrias/hosting_restapi/tree/civisplit (this is the civisplit branch, not included in this pull request).

I'll submit another pull request once this one is accepted.

**Comment by mlutfy** [comment]
Thanks!

**Pull request merged**
